# Generated by Django 5.1.1 on 2025-06-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
