# Generated by Django 5.1.1 on 2025-06-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodapp', '0002_moodentry_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
